# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Simple-SAX-Serializer
version:      0.04
version_from: lib/Simple/SAX/Serializer.pm
installdirs:  site
requires:
    Abstract::Meta::Class:                   0
    XML::SAX:                                0
    
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
